# permissions for end users to edit openstackprovisionservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstackprovisionserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-baremetal-operator
    app.kubernetes.io/part-of: openstack-baremetal-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstackprovisionserver-editor-role
rules:
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackprovisionservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackprovisionservers/status
  verbs:
  - get
