apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-baremetal-operator
    app.kubernetes.io/part-of: openstack-baremetal-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstackprovisionserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openstackprovisionserver-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackprovisionservers
  verbs:
  - get
  - list
- apiGroups:
  - baremetal.openstack.org
  resources:
  - openstackprovisionservers/status
  verbs:
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstackprovisionserver-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstackprovisionserver-role
subjects:
  # Applying the role to both SA (with and without prefix) to be able
  # to run the operator local
- kind: ServiceAccount
  name: openstack-baremetal-operator-openstackprovisionserver
  namespace: openstack
- kind: ServiceAccount
  name: openstackprovisionserver
  namespace: openstack
---
