apiVersion: baremetal.openstack.org/v1beta1
kind: OpenStackBaremetalSet
metadata:
  name: openstackbaremetalset
spec:
  # Define how many BaremetalHosts are desired to be provisioned and assign
  # a control plane IP to them
  baremetalHosts:
    compute-0: 172.22.0.100/24
    compute-1: 172.22.0.101/24
  # The image to install on the provisioned nodes
  osImage: edpm-hardened-uefi.qcow2
  # provisionServerName: openstack  # uncomment if you pre-deploy a separate OsProvServer (use its name for the value)
  # The secret containing the SSH pub key to place on the provisioned nodes
  deploymentSSHSecret: baremetalset-deploy-secret
  domainName: osptest.openstack.org
  # The interface on the nodes that will be assigned an IP from the mgmtCidr
  ctlplaneInterface: enp1s0
  ctlplaneGateway: 172.22.0.3
  # An optional secret holding a data entry called "NodeRootPassword"
  # This will be set as the root password on all provisioned BaremetalHosts
  passwordSecret: baremetalset-password-secret
